Switch to "github.com/edsrzf/mmap-go" for cross-platform mmap implementation
`syscall.Mmap` is not supported on Windows:
```
Error: lib/utils.go:86:23: undefined: syscall.Mmap
Error: lib/utils.go:86:70: undefined: syscall.PROT_READ
Error: lib/utils.go:86:89: undefined: syscall.MAP_SHARED
Error: lib/utils.go:90:16: undefined: syscall.Munmap
```